## Get Stage
name: Get Stage
run-name: Get Stage

on:
  workflow_call:
    outputs:
      stage:
        description: "stage"
        value: ${{ jobs.set_stage_variable.outputs.stage }}

jobs:
  set_stage_variable:
    runs-on: ubuntu-latest
    outputs:
      stage: ${{ steps.stage.outputs.stage }}
    steps:
      - name: Output stage
        id: stage
        run: |
          if [[ ${GITHUB_REF#refs/heads/} == "lian-test-canary" ]]; then
            stage="patch"
          else
            stage="canary"
          fi
          echo $stage
          echo "stage=${stage}" >> $GITHUB_OUTPUT


