name: Build uiconf
run-name: Build uiconf

on:
  workflow_call:
    secrets:
      PLAYER_CENTRAL_ACCOUNT_ID:
        required: true
      PLAYER_SERVICES_ACCOUNT_ID:
        required: true
      PLAYER_S3_BUCKET_DEPLOYMENT:
        required: true
    inputs:
      stage:
        description: "build for specific type - example: 'canary/beta/latest'"
        required: true
        type: string
      env:
        description: "env - example: 'qa/prod'"
        required: false
        type: string
      schema-type:
        description: "schema-type - example: 'playerV3Versions/playerV3OvpVersions'"
        required: true
        type: string
      uiconf-new-version:
        type: string
        required: false
        description: "not required - if no value is given it will increment the minor version - example 'from 1.00 to 1.01'"
    outputs:
      version:
        description: "version - example: '1.00.000'"
        value: ${{ jobs.build-uiconf.outputs.version }}
      file-name:
        description: "ini file name - example 'playkit_playerV3Versions_7.60.39_canary.ini'"
        value: ${{ jobs.build-uiconf.outputs.file-name }}

jobs:
  build-uiconf:
    runs-on: [ ubuntu-latest ]
    permissions:
      id-token: write
      contents: read
    outputs:
      version: ${{ steps.version.outputs.version }}
      file-name: ${{ steps.file_name.outputs.file_name }}
    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.PLAYER_CENTRAL_ACCOUNT_ID }}:role/central-oidc-github-actions
          role-session-name: githubAction
          aws-region: "eu-central-1"

      - name: Increase version and update ssm param
        id: version
        run: |
          # Assume role
          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
                      $(aws sts assume-role \
                      --role-arn arn:aws:iam::${{ secrets.PLAYER_SERVICES_ACCOUNT_ID }}:role/nvp1-deployment-role \
                      --role-session-name "nvp1-${{ github.run_id }}" \
                      --region "us-east-1" \
                      --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
                      --output text))

          if [ "${{ inputs.stage }}" = "canary" ]; then
            oldVersion=$(aws ssm get-parameters --names /player/versions/uiconf/canary --region us-east-1 | jq -r .Parameters[].Value)
            if [ "${oldVersion}" = "NULL" ]; then
              oldVersion=$(aws ssm get-parameters --names /player/versions/uiconf/latest --region us-east-1 | jq -r .Parameters[].Value)
              newVersion="${oldVersion}.001"
            else
              newVersion=$(echo "${oldVersion}" | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
            fi
          else
            oldVersion=$(aws ssm get-parameters --names /player/versions/uiconf/latest --region us-east-1 | jq -r .Parameters[].Value)
            if [ -z "${{ inputs.uiconf-new-version }}" ] ; then
              newVersion=$(echo "${oldVersion}" | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
            else
              newVersion=${{ inputs.uiconf-new-version }}
            fi

            if [ "${{ inputs.stage }}" = "latest" ]; then
              aws ssm put-parameter --name /player/versions/uiconf/canary --value "NULL" --overwrite --region us-east-1
            fi
          fi

          aws ssm put-parameter --name /player/versions/uiconf/${{ inputs.stage }} --value ${newVersion} --overwrite --region us-east-1

          echo "new version is: ${newVersion}"
          echo "version=${newVersion}" >> $GITHUB_OUTPUT

      - name: Build uiconf for ${{ inputs.stage }} on schema-type ${{ inputs.schema-type }}
        run: |
          # Assume role
          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
                      $(aws sts assume-role \
                      --role-arn arn:aws:iam::${{ secrets.PLAYER_SERVICES_ACCOUNT_ID }}:role/nvp1-deployment-role \
                      --role-session-name "nvp1-${{ github.run_id }}" \
                      --region "us-east-1" \
                      --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
                      --output text))

          if [ "${{ inputs.stage }}" = "canary" ]; then
            jsonNameSchema="player-canary-${{ inputs.schema-type }}.json"
          elif [ "${{ inputs.env }}" = "qa" ] && ["${{ inputs.stage }}" = "beta" ]; then
            jsonNameSchema="player-qa-beta-${{ inputs.schema-type }}.json"
          elif [ "${{ inputs.env }}" = "prod" ] && ["${{ inputs.stage }}" = "beta" ]; then
            jsonNameSchema="player-prod-beta-${{ inputs.schema-type }}.json"
          elif [ "${{ inputs.env }}" = "prod" ] && ["${{ inputs.stage }}" = "latest" ]; then
            jsonNameSchema="player-prod-latest-${{ inputs.schema-type }}.json"
          else
            jsonNameSchema="player-qa-${{ inputs.schema-type }}.json"
          fi

          s3PathSchema="s3://nvp1-${{ secrets.PLAYER_S3_BUCKET_DEPLOYMENT }}/player/schema"
          aws s3 cp ${s3PathSchema}/${jsonNameSchema} ${jsonNameSchema}
          jsonConf=$(cat ${jsonNameSchema} | jq -c '.')

          iniName="playkit_${{ inputs.schema-type }}_${{ steps.version.outputs.version }}_${{ inputs.stage }}.ini"
          s3Path="s3://nvp1-${{ secrets.PLAYER_S3_BUCKET_DEPLOYMENT }}/player/uiconf"

          tmp=$(mktemp)
          echo "[general]" > "$tmp"
          echo "component.name = ${{ inputs.schema-type }}" >> "$tmp"
          echo "component.version = ${{ inputs.stage }}" >> "$tmp"
          echo "" >> "$tmp"
          echo "[defaultKdp]" >> "$tmp"
          echo "objectType = 6" >> "$tmp"
          echo "widgets.versions.conf_vars = '{\"version\":\"${{ steps.version.outputs.version }}\"}'" >> "$tmp"
          echo "widgets.versions.name = playkitVersions" >> "$tmp"
          echo "widgets.versions.usage = list,${{ steps.version.outputs.version }},${{ inputs.schema-type }},${{ inputs.stage }}" >> "$tmp"
          echo "widgets.versions.config = '${jsonConf}'" >> "$tmp"

          mv "$tmp" ${iniName}

          aws s3 cp ${iniName} ${s3Path}/

      - name: Output file_name
        id: file_name
        run: |
          iniName="playkit_${{ inputs.schema-type }}_${{ steps.version.outputs.version }}_${{ inputs.stage }}.ini"

          echo "file name is: ${iniName}"
          echo "file_name=${iniName}" >> $GITHUB_OUTPUT