on:
  workflow_call:
    inputs:
        pluginPath:
          description: "The folder name of the plugin"
          required: true
          type: string
        bucket:
          description: "Bucket name"
          required: true
          type: string
        access_key:
          description: "Bucket name"
          required: true
          type: string
        access_secret:
          description: "Bucket name"
          required: true
          type: string
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: common
    runs-on: ubuntu-latest
    run: |
      echo ${{ inputs.pluginPath }}
      echo ${{ inputs.accbucketess_key }}
      echo ${{ inputs.access_key }}
      echo ${{ inputs.access_secret }}
